/**
 * Plugin manifest metadata.
 *
 * This is consumed by:
 * - `lib/index.js` to build the `IoPluginsCatalog`.
 * - Admin Tab tooling (runtime) to build the plugin config UI dynamically.
 */
const manifest = Object.freeze({
	schemaVersion: 1,
	type: 'IngestRandomChaos',
	defaultEnabled: false,
	supportsMultiple: true,
	title: {
		en: 'Random chaos generator',
		de: 'Zufalls-Chaosgenerator',
		ru: 'Генератор случайного хаоса',
		pt: 'Gerador de caos aleatório',
		nl: 'Willekeurige chaosgenerator',
		fr: 'générateur de chaos aléatoire',
		it: 'Generatore di caos casuale',
		es: 'Generador de caos aleatorio',
		pl: 'Generator losowego chaosu',
		uk: 'Генератор випадкового хаосу',
		'zh-cn': '随机混沌生成器',
	},
	description: {
		en: 'Demo/load generator that periodically injects messages.',
		de: 'Demo-/Lastgenerator, der periodisch Nachrichten einspeist.',
		ru: 'Генератор демонстрационных/загрузочных данных, периодически внедряющий сообщения.',
		pt: 'Gerador de demonstração/carga que injeta mensagens periodicamente.',
		nl: 'Demo-/laadgenerator die periodiek berichten injecteert.',
		fr: 'Générateur de démo/charge qui injecte périodiquement des messages.',
		it: 'Generatore di demo/caricamento che inietta periodicamente messaggi.',
		es: 'Generador de demostración/carga que inyecta mensajes periódicamente.',
		pl: 'Generator demonstracyjny/ładujący, który okresowo wstrzykuje wiadomości.',
		uk: 'Генератор демонстраційних/завантажувальних файлів, який періодично вводить повідомлення.',
		'zh-cn': '演示/负载生成器，可定期注入消息。',
	},
	options: {
		intervalMinMs: {
			order: 10,
			type: 'number',
			label: {
				en: 'Min interval (ms)',
				de: 'Minimales Intervall (ms)',
				ru: 'Минимальный интервал (мс)',
				pt: 'Intervalo mínimo (ms)',
				nl: 'Minimale interval (ms)',
				fr: 'Intervalle minimum (ms)',
				it: 'Intervallo minimo (ms)',
				es: 'Intervalo mínimo (ms)',
				pl: 'Minimalny odstęp (ms)',
				uk: 'Мінімальний інтервал (мс)',
				'zh-cn': '最小间隔（毫秒）',
			},
			help: {
				en: 'Minimum delay between ticks.',
				de: 'Minimale Verzögerung zwischen den Ticks.',
				ru: 'Минимальная задержка между тиками.',
				pt: 'Atraso mínimo entre os pulsos.',
				nl: 'Minimale vertraging tussen ticks.',
				fr: 'Délai minimum entre les ticks.',
				it: 'Ritardo minimo tra i tick.',
				es: 'Retraso mínimo entre ticks.',
				pl: 'Minimalne opóźnienie pomiędzy tikami.',
				uk: 'Мінімальна затримка між тиками.',
				'zh-cn': '最小时间刻度间隔。',
			},
			min: 500,
			max: 60000,
			default: 2000,
			step: 500,
		},
		intervalMaxMs: {
			order: 20,
			type: 'number',
			label: {
				en: 'Max interval (ms)',
				de: 'Maximales Intervall (ms)',
				ru: 'Максимальный интервал (мс)',
				pt: 'Intervalo máximo (ms)',
				nl: 'Maximale interval (ms)',
				fr: 'Intervalle maximal (ms)',
				it: 'Intervallo massimo (ms)',
				es: 'Intervalo máximo (ms)',
				pl: 'Maksymalny odstęp (ms)',
				uk: 'Максимальний інтервал (мс)',
				'zh-cn': '最大间隔（毫秒）',
			},
			help: {
				en: 'Maximum delay between ticks.',
				de: 'Maximale Verzögerung zwischen den Ticks.',
				ru: 'Максимальная задержка между тактами.',
				pt: 'Atraso máximo entre os pulsos.',
				nl: 'Maximale vertraging tussen ticks.',
				fr: 'Délai maximal entre les ticks.',
				it: 'Ritardo massimo tra i tick.',
				es: 'Retraso máximo entre ticks.',
				pl: 'Maksymalne opóźnienie pomiędzy tikami.',
				uk: 'Максимальна затримка між тиками.',
				'zh-cn': '两次数据滴答之间的最大延迟。',
			},
			min: 500,
			max: 60000,
			default: 5000,
			step: 500,
		},
		maxPool: {
			order: 30,
			type: 'number',
			label: {
				en: 'Max pool size',
				de: 'Maximale Poolgröße',
				ru: 'Максимальный размер бассейна',
				pt: 'Tamanho máximo da piscina',
				nl: 'Maximale zwembadgrootte',
				fr: 'Taille maximale de la piscine',
				it: 'Dimensione massima della piscina',
				es: 'Tamaño máximo de la piscina',
				pl: 'Maksymalny rozmiar basenu',
				uk: 'Максимальний розмір басейну',
				'zh-cn': '最大泳池尺寸',
			},
			help: {
				en: 'Maximum number of concurrent active messages.',
				de: 'Maximale Anzahl gleichzeitig aktiver Nachrichten.',
				ru: 'Максимальное количество одновременно активных сообщений.',
				pt: 'Número máximo de mensagens ativas simultâneas.',
				nl: 'Maximaal aantal gelijktijdig actieve berichten.',
				fr: 'Nombre maximal de messages actifs simultanés.',
				it: 'Numero massimo di messaggi attivi contemporaneamente.',
				es: 'Número máximo de mensajes activos simultáneos.',
				pl: 'Maksymalna liczba równoczesnych aktywnych wiadomości.',
				uk: 'Максимальна кількість одночасно активних повідомлень.',
				'zh-cn': '并发活动消息的最大数量。',
			},
			min: 1,
			max: 100,
			default: 10,
			step: 1,
		},
	},
});

module.exports = { manifest };
