/**
 * Plugin manifest metadata.
 */
const manifest = Object.freeze({
	schemaVersion: 1,
	type: 'BridgeAlexaShopping',
	defaultEnabled: false,
	supportsMultiple: true,
	title: {
		en: 'Alexa shopping list bridge',
		de: 'Alexa-Einkaufslisten-Bridge',
		ru: 'Мост списка покупок Alexa',
		pt: 'Ponte da lista de compras Alexa',
		nl: 'Alexa boodschappenlijst-bridge',
		fr: 'Pont de liste de courses Alexa',
		it: 'Bridge della lista della spesa Alexa',
		es: 'Puente de lista de compras Alexa',
		pl: 'Most listy zakupów Alexa',
		uk: 'Міст списку покупок Alexa',
		'zh-cn': 'Alexa 购物清单桥接',
	},
	description: {
		en: 'Bidirectional sync between an Alexa list (alexa2) and a Message Hub shopping list.',
		de: 'Bidirektionale Synchronisation zwischen einer Alexa-Liste (alexa2) und einer Message Hub Einkaufsliste.',
		ru: 'Двунаправленная синхронизация между списком Alexa (alexa2) и списком покупок Message Hub.',
		pt: 'Sincronização bidirecional entre uma lista Alexa (alexa2) e uma lista de compras do Message Hub.',
		nl: 'Bidirectionele synchronisatie tussen een Alexa-lijst (alexa2) en een Message Hub boodschappenlijst.',
		fr: 'Synchronisation bidirectionnelle entre une liste Alexa (alexa2) et une liste de courses Message Hub.',
		it: 'Sincronizzazione bidirezionale tra una lista Alexa (alexa2) e una lista della spesa di Message Hub.',
		es: 'Sincronización bidireccional entre una lista de Alexa (alexa2) y una lista de compras de Message Hub.',
		pl: 'Dwukierunkowa synchronizacja między listą Alexa (alexa2) a listą zakupów Message Hub.',
		uk: 'Двонаправлена синхронізація між списком Alexa (alexa2) та списком покупок Message Hub.',
		'zh-cn': '在 Alexa 列表（alexa2）与 Message Hub 购物清单之间进行双向同步。',
	},
	options: {
		jsonStateId: {
			order: 10,
			type: 'string',
			label: { en: 'Alexa list JSON state id', de: 'Alexa-JSON-State-ID' },
			help: {
				en: 'State id that contains the Alexa list items as JSON array (e.g. alexa2.0.Lists.SHOP.json).',
				de: 'State-ID, die die Alexa-List-Items als JSON-Array enthält (z.B. alexa2.0.Lists.SHOP.json).',
			},
			default: 'alexa2.0.Lists.SHOP.json',
		},
		listTitle: {
			order: 20,
			type: 'string',
			label: { en: 'List title', de: 'Listentitel' },
			help: { en: 'Message title in Message Hub.', de: 'Nachrichten-Titel in Message Hub.' },
			default: 'Alexa shopping list',
		},
		location: {
			order: 30,
			type: 'string',
			label: { en: 'Location', de: 'Ort' },
			help: { en: 'Written to message details.location.', de: 'Wird in details.location geschrieben.' },
			default: 'Supermarket',
		},
		audienceTagsCsv: {
			order: 40,
			type: 'string',
			label: { en: 'Audience tags (CSV)', de: 'Audience-Tags (CSV)' },
			help: {
				en: 'Comma-separated tags copied to message audience.tags.',
				de: 'Kommagetrennte Tags, die nach audience.tags kopiert werden.',
			},
			default: '',
		},
		fullSyncIntervalMs: {
			order: 50,
			type: 'number',
			unit: 'ms',
			label: { en: 'Full sync interval', de: 'Full-Sync Intervall' },
			help: {
				en: 'Periodic full sync interval; 0 disables.',
				de: 'Periodisches Full-Sync-Intervall; 0 deaktiviert.',
			},
			min: 0,
			max: 24 * 60 * 60 * 1000,
			step: 60 * 1000,
			default: 60 * 60 * 1000,
		},
		conflictWindowMs: {
			order: 60,
			type: 'number',
			unit: 'ms',
			label: { en: 'Conflict window', de: 'Konfliktfenster' },
			help: {
				en: 'Debounce window for conflict enforcement after outbound writes.',
				de: 'Debounce-Fenster für Konflikt-Enforce nach Outbound-Writes.',
			},
			min: 0,
			max: 60 * 1000,
			step: 250,
			default: 5000,
		},
		keepCompleted: {
			order: 70,
			type: 'boolean',
			label: { en: 'Keep completed items', de: 'Erledigte Items behalten' },
			help: {
				en: 'When disabled, completed items are deleted (also in Alexa).',
				de: 'Wenn deaktiviert, werden erledigte Items gelöscht (auch in Alexa).',
			},
			default: true,
		},
		aiEnhancement: {
			order: 80,
			type: 'boolean',
			label: { en: 'AI enhancement', de: 'AI-Enhancement' },
			help: {
				en: 'When enabled, the plugin can enrich list items (e.g. category assignment) using MsgHub AI.',
				de: 'Wenn aktiviert, kann das Plugin List-Items (z.B. Kategorien) über MsgHub AI anreichern.',
			},
			default: true,
		},
		categoriesCsv: {
			order: 90,
			type: 'string',
			label: { en: 'Categories (CSV)', de: 'Kategorien (CSV)' },
			help: {
				en: 'Comma-separated allowed categories for AI assignment. The last entry is used as fallback.',
				de: 'Kommagetrennte erlaubte Kategorien für AI-Zuweisung. Der letzte Eintrag ist der Fallback.',
			},
			default: 'Produce,Bakery,Dairy,Meat,Frozen,Pantry,Drinks,Household,Hygiene,Other',
		},
		aiMinConfidencePct: {
			order: 100,
			type: 'number',
			unit: '%',
			label: { en: 'AI min confidence', de: 'AI Mindest-Confidence' },
			help: {
				en: 'Minimum confidence required to accept an AI category. Otherwise the fallback category is used.',
				de: 'Mindest-Confidence für AI-Kategorien. Sonst wird die Fallback-Kategorie genutzt.',
			},
			min: 0,
			max: 100,
			step: 1,
			default: 80,
		},
	},
});

module.exports = { manifest };
